### ISSUE TITLE
Cannot create new batch with attached file

### ISSUE THREAD

**Issue by meganforbes** [collectionspace/collectionspace-csv-importer#97]
To duplicate - log in to CSV Importer, create a connection to Public Art Demo (publicart.collectionspace.org), create a Collectionobject batch w/the attached CSV. Hit start on preprocessing, and taken to a screen that says "We're sorry, but something went wrong. If you are the application owner check the logs for more information."

The file contains two column headers for fields that cannot be imported into (computed current location), but seems like it should just fail preprocessing vs. failing before you get there?

[MAPremainingpublishtoobjects.csv](https://github.com/collectionspace/collectionspace-csv-importer/files/6817892/MAPremainingpublishtoobjects.csv)

**Comment by kspurgin** [comment]
So this error actually happens before you start preprocessing. It happens when you click "Submit" on the "New Batch" form

This indicates more of an issue with the most basic of the CSV file structure. 

I ran the file through https://csvlint.io/ and it has 66 errors, all of which appear to be related to inconsistent line endings.

Will poke at it some more to see what the exact failure is and how to deal with it better.

**Comment by kspurgin** [comment]
So, the code to create a new batch starts...

```
class Batch < ApplicationRecord
  include WorkflowManager
  CONTENT_TYPES = [
    'application/vnd.ms-excel',
    'text/csv'
  ].freeze
  has_one_attached :spreadsheet
[...snip...]
  validates :spreadsheet, attached: true, content_type: CONTENT_TYPES
[...snip...]
```

When I do `file --mime-type -b gh97.csv` in the command line, it returns: `text/plain`

So I am going to add `text/plain` to the list of allowed content types and see if that fixes things. 
```

**Comment by kspurgin** [comment]
No, it did not fix things. Testing in local dev env on master branch *and* my fix branch, I get the following in web log:

```
 Started GET "/batches/new" for 127.0.0.1 at 2021-07-14 14:52:48 -0400
Processing by BatchesController#new as HTML
  User Load (2.7ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Group Load (2.2ms)  SELECT "groups".* FROM "groups" WHERE "groups"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/policies/batch_policy.rb:16:in `new?'
   (3.1ms)  SELECT COUNT(*) FROM "connections" WHERE "connections"."user_id" = $1 AND "connections"."group_id" = $2 AND "connections"."enabled" = $3  [["user_id", 1], ["group_id", 1], ["enabled", true]]
  ↳ app/policies/batch_policy.rb:16:in `new?'
  Connection Load (2.6ms)  SELECT "connections".* FROM "connections" WHERE "connections"."user_id" = $1 AND "connections"."group_id" = $2 AND "connections"."primary" = $3 ORDER BY "connections"."id" ASC LIMIT $4  [["user_id", 1], ["group_id", 1], ["primary", true], ["LIMIT", 1]]
  ↳ app/models/user.rb:43:in `default_connection'
  Connection Load (2.4ms)  SELECT "connections".* FROM "connections" WHERE "connections"."user_id" = $1 AND "connections"."group_id" = $2 AND "connections"."enabled" = $3 ORDER BY "connections"."id" ASC LIMIT $4  [["user_id", 1], ["group_id", 1], ["enabled", true], ["LIMIT", 1]]
  ↳ app/models/user.rb:44:in `default_connection'
  Rendering batches/new.html.erb within layouts/application
  Rendered shared/_icon.html.erb (Duration: 1.2ms | Allocations: 179)
  Role Load (2.8ms)  SELECT "roles".* FROM "roles" WHERE "roles"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/models/user.rb:34:in `admin?'
  Role Load (2.3ms)  SELECT "roles".* FROM "roles" WHERE "roles"."name" = $1 ORDER BY "roles"."id" ASC LIMIT $2  [["name", "Admin"], ["LIMIT", 1]]
  ↳ app/models/role.rb:12:in `block in <class:Role>'
  CACHE Role Load (0.0ms)  SELECT "roles".* FROM "roles" WHERE "roles"."name" = $1 ORDER BY "roles"."id" ASC LIMIT $2  [["name", "Admin"], ["LIMIT", 1]]
  ↳ app/models/role.rb:12:in `block in <class:Role>'
  Group Load (2.3ms)  SELECT "groups".* FROM "groups"
  ↳ app/views/batches/_form.html.erb:23
  Connection Load (2.2ms)  SELECT "connections".* FROM "connections" WHERE "connections"."user_id" = $1 AND "connections"."group_id" = $2  [["user_id", 1], ["group_id", 1]]
  ↳ app/views/batches/_form.html.erb:32
  Mapper Load (2.6ms)  SELECT "mappers".* FROM "mappers" WHERE (title LIKE '% (core-6-1-0)') AND "mappers"."enabled" = $1 ORDER BY "mappers"."title" ASC LIMIT $2  [["enabled", true], ["LIMIT", 1]]
  ↳ app/views/batches/_form.html.erb:43
  Mapper Load (2.6ms)  SELECT "mappers".* FROM "mappers" WHERE (title LIKE '% (core-6-1-0)') AND "mappers"."enabled" = $1 ORDER BY "mappers"."title" ASC  [["enabled", true]]
  ↳ app/views/batches/_form.html.erb:42
  Rendered batches/_field_definitions.html.erb (Duration: 1.2ms | Allocations: 341)
  Rendered batches/_form.html.erb (Duration: 51.3ms | Allocations: 16520)
  Rendered batches/new.html.erb within layouts/application (Duration: 61.0ms | Allocations: 20039)
Completed 500 Internal Server Error in 108ms (ActiveRecord: 27.9ms | Allocations: 31995)



ActionView::Template::Error - undefined method `row' for "#<Csvlint::ErrorMessage:0x00007ff5e93ed0a0>":String:
  app/views/batches/_form.html.erb:115:in `view template'
  app/views/batches/new.html.erb:3

Started POST "/__better_errors/acf8ce4a207f1899/variables" for 127.0.0.1 at 2021-07-14 14:52:49 -0400
```

**Comment by kspurgin** [comment]
Ok, so the above error is because the web page template for the form (in the case of an invalid CSV) was somehow being sent the **string** "#<Csvlint::ErrorMessage:0x00007ff5e93ed0a0>" instead of a Ruby Csvlint::ErrorMessage **object**. 

I do not like how these errors were supposed to be displayed anyway, or the fact that they were limited to showing 5 errors. 

I have made it so you see the following at the bottom of the form if your CSV is invalid instead: 

![image](https://user-images.githubusercontent.com/450570/125686393-c45c75ba-47c0-4578-8449-bcf40e91f861.png)

**Comment by kspurgin** [comment]
@meganforbes - So, we can't fix this because the problem is with the CSV file structure. The CollectionSpace CSV Importer is not intended to be a CSV editor or remediation tool, and requires CSVs that follow a basic [standard CSV dialect](https://specs.frictionlessdata.io/csv-dialect/#specification).

#98 is going to "fix" this problem by showing the message shown in the previous message. 

Running this file through https://csvlint.io/ gives more informative/friendly information about what is wrong with the file than we can hope to in CollectionSpace CSV Importer.

Unfortunately, its "Download Standardised CSV" button did NOT magically fix the issue.

However, opening the file in LibreOffice Calc and then doing a "Save as..." a new .csv file did fix the issue. 

Given that LibreOffice Calc is a dedicated tabular data editing/creation application, it makes sense they have been able to build in a lot more sophisticated "auto fixing" than could ever be included in the Importer.
